services:
  web-stack-config:
    image: nginx:alpine
    ports:
      - "8081:80"
    configs:
      - source: nginx_conf_v2
        target: /etc/nginx/conf.d/default.conf
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s

configs:
  nginx_conf:
    file: ./nginx.conf