version: "3.8"

services:
  api:
    image: tipoit/simple-api:1.1   # или registry.local/simple-api:1.0
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: app
      DB_USER: app
      DB_PASSWORD: secret
    networks:
      - backend
    ports:
      - "8000:8000"        # публикуем API наружу через routing mesh
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - node.role == manager    # пример, можно убрать/заменить
      restart_policy:
        condition: on-failure

networks:
  backend:
    driver: overlay

volumes:
  db_data: